### ISSUE TITLE
Greenland example: error in compiling the friction code

### ISSUE THREAD

**Issue by tmitcham** [ggslc/bisicles-camip#3]
running `gmake all` from the $BISICLES_HOME/bisicles-camip/examples/Greenland directory produces the following error message:

``GNUmakefile:17: *** target file `clean' has both : and :: entries.  Stop.``

removing lines 17 - 21 (the clean and realclean options) from GNUmakefile bypasses this error but produces the following error:

`Fatal Error: Cannot open module file ‘netcdf.mod’ for reading at (1): No such file or directory`
`compilation terminated.`

**Comment by ggslc** [comment]
Removed this example since it would be out of date even if it did work

**Comment by ggslc** [comment]
Removed this example since it would be out of date even if it did work
