### ISSUE TITLE
Update number of arguments to python basal melt functions

### ISSUE THREAD

**Issue by tmitcham** [ggslc/bisicles-camip#4]
Basal melt function definitions (e.g. in MISMIP+ example) using the Python interface (in `shortshallow.py`) only provide 5 arguments, whereas the interface now expects 6 arguments to be provided (including the ice fraction).

A temporary fix is to add `*etc` as a 6th argument to the basal melt function definitions but will need to update these examples eventually.

**Comment by ggslc** [comment]
example s CalvingRate/plane.py DamageModel/shortshallow.py MISMIP+/shortshallow.py PythonChannel/gaussianChannel.py updated
